sudo: required
language: scala
scala:
- 2.11.6
services:
- docker
env:
  global:
  - TERM=dumb
  - secure: AfSTm/v/UomT+HAfqRRD5lglM/JBCTAmd0whAmW8JFN3aJo0qNK+mASsIMy/VM3sGl4nH65vt85BOuiLO2QLSDeFZCg9Y/lYBtGl3zwarjQ2+kzehl2IXs5s9wwECx0t+CrmvQXqFdArMkxAFDHCSP62B7pNWrpocEOejaZpVqrBJxYorYZ0PFXG5kZmb9EUndSHkO97YqiB7cE8R1P8ddwytWDgKqbgjpEqJDU3HA44/WSIXBg5fp7/Ij7VXMhI1ElvAMvRUndiLyEf4nSmStsIDj8JqEzxF9Pw82yOooA9D+Kbv3deBM9bKUs2gpgR7eFvUyKbL24v3WsA+ow381tjWdOgknV9mbqiwKaxoOxEdzmH57VjZ2T0JtG98fpqcOUkKOJHyeyHU8dRCENzs6Ow0FLHFP6A0kTf4vHxkdrgHkMSy7s4EpubCFOspNYiyl7EQ51DW9Jc+7rjoZ9qpjS4AjLsC45T07vjgDRUnuJfv5BWI8q9vMjU3hfYq6xLnOUjFAlmT/xuSEL1Lkng80ZZ+Y2boQIh8QvEAWdRhPJs+PU9adr6NaL3H2t7algC4xmr5x+E7tfmDAZGBw9nv/yZuhUloSR1a0jofUrfMaM8b+Eh0wCulh4o2MkoTF74rzvFOGe2kjo1GcS5FT4sq2LRSco1I8UXbSbPsp5fiC0=
  - secure: sAM1ujdBrUIqm4J7xg1tjEpoXx78qS9Bokl6CGNNJgG/IWsAS8d0aE9OWUUTwKjBMFc9e/ZRsg7d62TcSpanq/tys0HM0k53tebPinfvt8uT1ZFRKEtYvCP5V0KNufJdpt1tNgyUilLfQ4R/5T4BvygNiOKJWHaZppw5YkmIBQFv2/HONvCHMAasLXnWlL1+arQvAy0X/NUN8Sp1X0mme1ngrZMDkyz59jUJj8PwyTm7fG6B6F0bFwQTbD1SfYE/1qj+0j0Qtyuq50d1YeQQINthio9XZPU41BS1jwuBc32xLLSyxeKpBmuUIa4IzsZEzyFA+QkRF8Kj7pKAdFSWIf079jcTnxCHZVw/hiWNYyXQw23xrJxB/eLOdcDBnfZ/BT1/YXZiDe6XGuVKUJIlBUjD10qdSdKCCTLptjARe2XrLn5OiEu/eNJogq+ThrLrPINyYz394Tqzr0AHIkFz7src+HXIIfOQnVDCyeltNm2rm7OmB7SgfAQgVldwYHj/lfGSjW+yiEnllaVAs6EkEZ3pMlXPrKU+f1SOG6i1wgi9bVSeCxms6vOQ98q3kkpRkTVxevekE4TkXQoeSaJHY+ONrzorT4GMKVqSMjMBaL701wwJQD4YO9SheP/uRL5aOQacJ91wKK6GlAMcaj0QMI9wrNAUPyDUTFf4IiPBjoc=
  - secure: T+iQ7cIqqkp6F2FvGVgWvFjBlFlbRnsvtLarZ+edhBp0LxH/25dR/XHtEKyzzbgsnMthMUNKOh1D4/k9/R1UxvztrT/KzKzJXnI9Eb2DIdklwduLYvPzIuPHyt3In9iac5PZsaTUIbv6kQFZEhMvdOGRrEdKcbGJ4TgtD1XR6lF2kGNKCPbLUOmGqOD5pgiY2arLu1ZnDHbteU/HKV3Fi90ZdciGrReFrGCl650jMRCB5UkGCLiq0zbIijqs69P/vmts4n2AOmKpg57V+2XBNXqZslNSWV/8efVnc5UrwYaXAyUl6jBuY4xV4Qbiqw7V3G70WXmyM0U1+gaeEMisLxlvRRXoKP7K+FPEhq57Tk9RHM1yZYmd22MxwnJY5BwRHPhBmCpAO6YGDf6Ggtv6bYwsQmy7sQXKvYdGLNzp7bucWJ8weN2N7tbXL3dl5bUQxScczkn1iK8BIB/m4EHJhLD4IEhjYbjsnqzuAdw3ezWtsWtT/X0qP5oaz7KW5IEw6q0N6yRZqPayQKTwcfgE2B2ha7vhSvricLWyRkKllgfvLeYCJ8z4wU9sylrJsThCjkrC6uAf19WTUzcZthLbKrATeySvQ7cfK56X42S7qZZ0yETpohwhS22iE3L/W+ZgpV1LS3yl1wboomRZBN+24uFkE9RBOdSkHvY79fmpIJo=
notifications:
  email: false
install: true
before_install:
- "./tools/travis/setup.sh"
script:
- "./tools/travis/build.sh"
