sudo: required
language: scala
scala:
- 2.11.6
language: node_js
node_js:
- "stable"
services:
- docker
env:
  global:
  - TERM=dumb
  - secure: Cmv+Q3uYwtkU7DGqTRk05N+6z8WhEBg9VczPgAJXWgiWN4an0OgD/vVbnPqgqRNcQxV1Vj6lhYWR4eaAJvPRdXl0Uc8G0U6peMwvpRFIluK0w8bMFxEoQ9eMi3vMDsuOxCHfDNY37bpZjxIEqz75Xz3JEzjPaJGAK4Lx58a3RZIu6cNuGcN2RWsWT2RDFTANejzlMvzahOBR8MW0xKEZcovb0IRV3hkS2LL6IcpZYJntCCJeYOShcXnX3H28jKbu16EbBVNDbrVlhI+USnOem9DcjrSShddRekYbKN1gxOCtCIcf+3mzcHAHAl1Z/Z+Mo5JZihXvyWGPqmLd2v5AvIZIglQ9n3N1RScNekn3vchqFCB7stkyO7rr1Q/ffPfPFVVvd7zoQsxYmXHPL95eNMtf0BhQoo+U1IERoVf9T9NO/8fUrrdQRuUJwT0w3PYB2RtW5E5TSndTsH1StpjpkMDyVyq9OPri52bVQ3TDllQrPVXh6glOVJmdL7YS/4wwG2w6xgtXq+xJghhGJ6cDZnFvS5pKxzFc3fyuw/6Kx4zzPIVdFEPFFafoWOBua8mfb2/UTE1gkVcht+2PmdwIT7ffBc48XdJPU6ju0HgckoDG6s9z27YsJxlPQKxoOAUB8Il4Wtgjv2ug3RVSr372Mg275z5pjkWTDj1tc1bT8QE=
  - secure: DcwNORlWfdmceO/ViavMNxlB9DJrnbtAvGQ5AisRp6iwvtLH1etwpQYPLfWiDD3BnexdSxWXH8C6Y4oqlW9+sFA5Mc1a+PoMLrMhqKbyUNoa/mOVqbVqeyB3SLtZUVDBxZ7J4794r9SnN9GdG2FFGUGMPLTtDBl/R0EnCYyvyK+6kk0mYhTe+lv1lHMkoeq6Vay1byk+L/WkRX/Q+TD8GIsAsKYJRZYXC2vKWPxGFsPJVV/ybGD9PG0XJnCkRLJcviIggfNQTNmDFyNIYOVaYIBOFDpbR6VJGEtrS7qfoYLXbe46Nl1exg+nR+RRwOJxm1AaNlcnYZID7Cu/Fz3OJvmpcSVnew3wz0hCddlP4TNF3oKQe4NBItbb/P3P8OGoClTR9Wyc8Ob+BVIuR5bnk6BzF18YORvexcUfyPP2i6yGwD7pB0UoMYC2BinrcJZvm8oHNq2friXHi+lcCe/kKcseaJDmTgFewgn/LO0KfAkk9vRj2nbLt9IM4aVgALypUqsFTa9myBw+/tYNVe8UHRpDkwVLfUtY5f692KhP/fS9Lhv2cgX9V6vm5/YECm1WWnDL/Is4bgn9cYEqS/EXUwrJ4F/Z2fOSW2lwoabVNAyRtmclXPowiN4IIYgjS2L1bwav0zoDeXTOQ1a5Z+SNXmnNeqfAsWYgMZtqIhuX4uU=
  - secure: gBII6Uwgh8MLVM9iItE1yKjys1cA2lADcP/QgQepPSueu0mghS8CmH5waUWyKxMMFYvnlfCQu7LukcWiNs8J3VUjIswPgCUeALEwlBBquyrP5SeGFtdx3Ol3qzN8pTnnnV1t8WVScjZ/ssm+9oT4SWmdcxG8wldTewL/kNfVlZsENeFMyNwUoEBnAqNpzbDzN8+f5U1LTfk9TY3BGrbMvBencUQofOJR24EHnaDlx8SYbKzy1Uh+2KSxTdBvSosi12TjbWMSPWnBZo/rd7ytzBYvA0LYv9H1+X01cxa6S0ToTw8sJ8pMnfYbnchFV46DYAcJIdl0GXzNI9i171O3N745O09w9u67pbZGsYkohdlE9FaMBeTDb25lh3RX7wJEBnDYebajefSlBFWVTqItseTSn+j1wZUy4M4HNolOHqsH2DBfEsEW1UGr5y2/0Zm1RiE443eXS6UhE76rt3fS5907D0lVpt7puuZTew6L+Rse0bVv+bnEhw1pQAbppAGlnJ0z15+mZ13DR0xxRGspnZQFQdU5hWcbHMx/m9p7ykc+ms1rIzd6YpuSiEkpHfDr57WhkjPvZemF5oGDhY8H2nd+Ri6ZSR0Qgqvf+jNeEls/sHwsGRe2HC0my+BzhJR/5kXgW9pt75zk42OF2NL9zO8cpCFxYCFCFC1y+4dltvg=
notifications:
  email: false
install: true
before_install:
- "./tools/travis/setup.sh"
script:
- "./tools/travis/build.sh"
- "npm run test"
