/**
 *
 * This action will take an inbound message (that was not generated by this app)
 * and return a response message if the content matches specific criteria.
 *
 * The inbound params should contain the following properties:
 * myEvent - Bool - Was the message generated by this app. Use this to avoid message loops
 * spaceId - string - the space that the message originated from
 * content - string - the content of the message
 *
 * The results are intended to be input for the WWSendMessage action:
 * spaceId - string - the target space for the new message
 * title - string - the title used for the new message
 * text: - string - the text for the new message
 *
 */

var _ = require("lodash");

function main(params) {
  return new Promise((resolve,reject) => {
    if (params.type.startsWith("message-") && !params.type.startsWith("message-annotation-")) {
      resolve(params);
    }
    else if (params.hasOwnProperty("annotationType") && params.annotationType === "generic") {
      resolve(params);
    }
    else {
      reject(params);
    }
  });
}
